baseURL = 'https://nyxipedia.com/'
languageCode = 'en-us'
title = 'Nyxipedia'
theme = "book"

[markup]
[markup.tableOfContents]
  startlevel = 1
[markup.goldmark.renderer]
  unsafe = true
  xhtml = true
[params]
BookTheme = 'dark'
BookSection = '*'
BookToC = false
BookRepo = 'https://github.com/isugimpy/nyxipedia'
BookCommitPath = 'commit'
BookEditPath = 'edit/main'
